package br.edu.ifpb.pdm.orgulhogeek;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.AdapterView;
import android.widget.GridView;
import android.widget.ListView;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    ListView lvSagas;
    GridView gvSagas;
    List<Saga> sagas = new ArrayList<Saga>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        this.sagas.add(new Saga("Star Wars", "Star Wars é o título de uma \"ópera espacial\", nas próprias palavras do seu autor que assim designou o universo de fantasia que compunha este projeto, que foi transformada em uma série de nove filmes de ficção científica.", R.drawable.saga_minimalist_sw, 4.6));
        this.sagas.add(new Saga("Senhor dos Anéis", "Localizada no mundo ficcional na Terra Média, os três filmes seguem o jovem hobbit Frodo Baggins em sua missão de destruir o \"Um Anel\", assegurando assim também a destruição de seu criador, o Senhor das Trevas Sauron. Para auxiliá-lo em sua tarefa, forma-se uma sociedade, composta por representantes dos humanos, hobbits, elfos e anões, encarregados de sua segurança pelos estranhos caminhos que terá que seguir. No entanto, a sociedade quebra-se e Frodo continua sua jornada sozinho, apenas acompanhado por seu amigo fiel, Samwise Gamgee, e pelo traiçoeiro Gollum, um dos antigos possuidores do \"Um Anel\". Ao mesmo tempo, o mago Gandalf e o humano Aragorn, herdeiro exilado do trono de Gondor, unem-se e juntam o Povo Livre da Terra Média em uma guerra, finalmente vitoriosa, contra Sauron.",R.drawable.saga_minimalist_lotr, 4.9));
        this.sagas.add(new Saga("Harry Potter", "Até hoje, a saga Harry Potter é a franquia de maior bilheteria de todos os tempos, com os oito filmes lançados faturando mais de 7,7 bilhões de dólares em todo o mundo. Sem o ajuste para a inflação, isso é maior do que os 23 filmes de James Bond e os seis filmes da franquia Star Wars. A Pedra Filosofal, de Chris Columbus, se tornou a maior bilheteria de Harry Potter em todo o mundo em 2002, mas foi ultrapassada por Relíquias da Morte: Parte 1 e logo depois pela Parte 2, ambas de David Yates. Prisioneiro de Azkaban, de Alfonso Cuarón, foi o filme que menos arrecadou.",R.drawable.saga_minimalist_hp,4));
        this.sagas.add(new Saga("Doctor Who", "Doctor Who é uma série de ficção científica britânica, produzida e transmitida pela BBC desde 1963. A série mostra as aventuras do Doutor (The Doctor), um Timelord, - alienígena do planeta Gallifrey - que explora o universo em sua máquina do tempo, uma sensível nave espacial conhecida como T.A.R.D.I.S. (Time And Relative Dimension In Space), cuja aparência exterior se assemelha a uma cabine de polícia londrina de 1963. Juntamente com os seus companheiros, O Doutor enfrenta uma variedade de inimigos, enquanto trabalha para salvar as civilizações, ajudar as pessoas comuns e corrigir erros. Embora uma das grandes constantes da série “Doctor Who” seja que ninguém sabe seu nome real.", R.drawable.saga_minimalist_dw, 4.5));
        this.sagas.add(new Saga("Game of Thrones", "Há muito tempo, em um tempo esquecido, uma força destruiu o equilíbrio das estações. Em uma terra onde os verões podem durar vários anos e o inverno toda uma vida, as reivindicações e as forças sobrenaturais correm as portas do Reino dos Sete Reinos. A irmandade da Patrulha da Noite busca proteger o reino de cada criatura que pode vir de lá da Muralha, mas já não tem os recursos necessários para garantir a segurança de todos. Depois de um verão de dez anos, um inverno rigoroso promete chegar com um futuro mais sombrio. Enquanto isso, conspirações e rivalidades correm no jogo político pela disputa do Trono de Ferro, o símbolo do poder absoluto.",R.drawable.saga_minimalist_got, 4.2));
        this.sagas.add(new Saga("Universo Marvel", "O Universo Cinematográfico Marvel é uma franquia de mídia americana e um universo ficcional compartilhado que é centrado em uma série de filmes de super-heróis, produzidos de forma independente pela Marvel Studios e baseados em personagens que aparecem em publicações pela Marvel Comics. A franquia tem se expandido para incluir histórias em quadrinhos, curtas-metragens, séries de televisão e séries digitais. O universo compartilhado, muito parecido com o Universo Marvel nos quadrinhos, foi estabelecido por cruzar elementos comuns do enredo, cenários, elenco e personagens.",R.drawable.saga_minimalist_avengers, 3.5));
        this.sagas.add(new Saga("Star Trek", "Star Trek é uma franquia de entretenimento norte-americana criada por Gene Roddenberry. A franquia iniciou-se como uma série de televisão em 1966, originalmente chamada Star Trek mas posteriormente renomeada para Star Trek: The Original Series.\nAs histórias de Star Trek normalmente mostram as aventuras de humanos e alienígenas que servem a Frota Estelar, uma armada pacífica que serve a Federação Unida dos Planetas. Os personagens são essencialmente altruístas, cujos ideais são aplicados nos dilemas apresentados na série. Os conflitos apresentados em Star Trek às vezes representam uma alegoria para conflitos contemporâneos: a série original discute questões da década de 1960, assim como seus spin-offs refletem as questões de suas respectivas décadas. Questões refletidas nas séries incluem: guerra e paz, lealdade, autoritarismo, imperialismo, economia, racismo, religião, direitos humanos, sexismo, feminismo e o papel da tecnologia. Roddenberry disse: \"[Ao criar] um novo mundo com novas regras, eu podia discutir sobre sexo, religião, Vietnã, política e misseís intercontinentais. Realmente, nós as colocamos em Star Trek: nós estávamos mandando mensagens e felizmente elas passaram pela emissora\".",R.drawable.saga_minimalist_startrek, 4));
        this.sagas.add(new Saga("Matrix", "Em um futuro próximo, Thomas Anderson, um jovem programador de computador que mora em um cubículo escuro, é atormentado por estranhos pesadelos nos quais encontra-se conectado por cabos e contra sua vontade, em um imenso sistema de computadores do futuro. Em todas essas ocasiões, acorda gritando no exato momento em que os eletrodos estão para penetrar em seu cérebro. À medida que o sonho se repete, Anderson começa a ter dúvidas sobre a realidade. Por meio do encontro com os misteriosos Morpheus e Trinity, Thomas descobre que é, assim como outras pessoas, vítima do Matrix, um sistema inteligente e artificial que manipula a mente das pessoas, criando a ilusão de um mundo real enquanto usa os cérebros e corpos dos indivíduos para produzir energia. Morpheus, entretanto, está convencido de que Thomas é Neo, o aguardado messias capaz de enfrentar o Matrix e conduzir as pessoas de volta à realidade e à liberdade.",R.drawable.saga_minimalist_matrix,4));
        this.sagas.add(new Saga("Universo DC", "O Universo DC é um ambiente fictício onde ocorrem a maioria das histórias publicadas pela DC Comics. Super Homem, Batman, Flash, Mulher Maravilha e Lanterna Verde são os super-heróis mais conhecidos deste universo.\nOs principais heróis do Universo DC surgiram nos anos 1940. A maioria das histórias situadas neste ambiente têm lugar em cidades fictícias, como Gotham City e Metrópolis, a primeira incorporando os aspectos negativos da vida em uma cidade grande e a segunda refletindo os aspectos positivos. A presença dos super-heróis afetou as cidades, mas suas histórias fictícias em geral são similares à história dos Estados Unidos.",R.drawable.saga_minimalist_dc,3.9));
        this.sagas.add(new Saga("De Volta para o Futuro", "A saga De Volta para o Futuro, criada e dirigida por Robert Zemeckis, acompanha as aventuras de um rapaz chamado Marty McFly, interpretado por Michael J. Fox. No primeiro filme, lançado em 1985, Marty e seu excêntrico amigo cientista, Dr. Emmett L. Brown (Christopher Lloyd), vivem uma curiosa aventura a bordo de uma máquina do tempo instalada em um carro DeLorean, viajando por diferentes períodos da história de Hill Valley, na Califórnia. Depois de uma confusão, Marty usa sem querer a invenção do doutor e acaba voltando no tempo, para o dia 05 de novembro de 1955. O principal incidente é que a mãe de Marty se apaixona por ele, ao invés do seu pai, criando um possível problema que alteraria a história atual (no caso, de 1985). Na segunda aventura, lançada em 1989, a dupla viaja acompanhada por Jennifer (Elisabeth Shue) para 2015. No futuro, eles encontram a família de Marty em ruínas. O filme ainda inclui outras viagens, com direito a um alternativo 1985 e o retorno a 1955. A trilogia chegou ao fim em 1990, com Doc Brown preso em 1885 e Marty tendo que resgatá-lo, ajudando-o a consertar a DeLorean. No passado, Doc se apaixona pela professora Clara Clayton (Mary Steenburgen) e considera a possibilidade de ficar no velho oeste. Cabe a Marty convencer o doutor a voltar ao presente antes que seja tarde demais.", R.drawable.saga_minimalist_backtothefuture, 3.7));
        this.sagas.add(new Saga("X-Men", "A série de filmes X-Men é composta por filmes de super-heróis baseados na equipe de super-heróis de mesmo nome, criados por Stan Lee e Jack Kirby em 1963, que aparecem em publicações da Marvel Comics. ", R.drawable.saga_minimalist_xmen,2.5));
        this.sagas.add(new Saga("Alien", "Alien é um filme norte-americano de 1979 dirigido por Ridley Scott e protagonizado por Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton, John Hurt, Ian Holm e Yaphet Kotto. O título do filme refere-se ao antagonista primário: uma criatura alienígena altamente agressiva que persegue e mata a tripulação de uma nave espacial. Dan O'Bannon escreveu o roteiro do filme baseado em uma história criada por ele e por Ronald Shusett, tirando inspiração de trabalhos anteriores de ficção científica e terror. O sucesso de Alien criou uma franquia de livros, quadrinhos, jogos e brinquedos, como também três sequências e duas prequências. Também lançou a carreira de Weaver, dando a ela seu primeiro papel principal, e a história dos encontros de Ripley com os alienígenas se tornou a base para as histórias das sequências: Aliens (1986), Alien 3 (1992) e Alien Resurrection (1997).", R.drawable.saga_minimalist_alien,4));
        this.sagas.add(new Saga("O Exterminador do Futuro", "A saga O Exterminador do Futuro é uma franquia que gira em torno de um universo protagonizado por ciborgues conhecidos como o Exterminadores, cuja missão principal é a luta contra a resistência humana.", R.drawable.saga_minimalist_terminator,2));
        this.sagas.add(new Saga("Planeta dos Macacos", "Planeta dos Macacos é uma franquia de mídia de ficção científica estadunidense que consiste em filmes, livros, séries de televisão e outras mídias sobre um mundo onde seres humanos e macacos inteligentes se confrontam. A série começou com o autor francês Pierre Boulle na novela de 1963 La Planète des Singes. A adaptação para o cinema de 1968, Planet of the Apes, foi um sucesso comercial e de crítica, iniciando uma série de sequências, tie-ins, e obras derivadas.", R.drawable.saga_minimalist_apes,3.5));
        this.sagas.add(new Saga("Battlestar Galactica", "Segundo a série, os humanos surgiram em um planeta distante chamado Kobol, em um passado longínquo. Com o tempo, esse planeta não pôde mais suportar a vida e os humanos, organizados em treze tribos - sendo que uma se perderia das demais (insinuando que esta seria nossa cultura atual) -, tiveram que procurar outro planeta em outro sistema solar. Milhares de anos depois de estarem instalados em novas colônias, com a evolução, a tecnologia avançou muito e a inteligência artificial usada pelos humanos ganhou status de forma de vida e consciência própria, se revoltando contra seus criadores por achar que estes não davam valor à sua existência Os Cilônios (assim chamados em português), acreditavam em um Deus único (monoteísmo) e os Humanos em vários (politeísmo), causando conflito entre suas culturas. Os Cylons então executaram um plano de destruição em massa que reduziu a Humanidade (cerca de 12 bilhões de pessoas) a alguns poucos milhares de sobreviventes. Sem alternativas, esses sobreviventes decidiram, sob a liderança do Comandante Adama, procurar por uma lendária décima terceira tribo, que havia deixado Kobol antes das outras doze tribos e havia se dirigido \"a um planeta brilhante conhecido como Terra\".", R.drawable.saga_minimalist_battlestar,3.2));


        lvSagas = (ListView) findViewById(R.id.lvSagas);
//        ArrayAdapter<Saga> adapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, this.sagas);
//        lvSagas.setAdapter(adapter);

        SagaAdapter adapter = new SagaAdapter(MainActivity.this, MainActivity.this.sagas);
        lvSagas.setAdapter(adapter);

        lvSagas.setOnItemClickListener(new AdapterView.OnItemClickListener(){
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Intent it = new Intent(MainActivity.this, SagaActivity.class);
                it.putExtra("SAGA", MainActivity.this.sagas.get(position));

                startActivity(it);
            }
        });



    }
}
